name: Documentation

on:
  workflow_dispatch: #Trigger manually (from main branch) OR whenever there are pushes on the release branch
  push:
    branches:
        -release

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    # Build the HTML documentation
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.9.1
      with:
          working-directory: ./documentation
          doxyfile-path: ./Doxyfile
    
    # Deploy the HTML documentation to GitHub Pages
    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation/html/
        destination_dir: ./docs/
        enable_jekyll: true
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages
