name: Build and functionality tests

# Builds LAMMPS from a reusable workflow and then executes all PAPRECA tests


on:
  schedule: #Test runs everyday at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

  
jobs:

  setCloneName:
    runs-on: ubuntu-latest
    outputs:
      clone_name: ${{ steps.set-clone-name.outputs.clone_name }}
    steps:
      - name: Set clone name variable
        id: set-clone-name
        run: echo "clone_name=release" >> $GITHUB_OUTPUT
        
  build-reusable:
   needs: setCloneName
   uses: sntioudis/papreca/.github/workflows/build-reusable.yml@main
   with:
     clone_type: branch
     clone_name: ${{ needs.setCloneName.outputs.clone_name }}
     cache_lammps: true

     
  sourceTests:
  
    needs:
      - setCloneName #required to retrieve the clone name
      - build-reusable
    
    runs-on: ubuntu-latest

    steps:

    - name: Checkout #Checkout PAPRECA repository
      uses: actions/checkout@v4 

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install mpich
        sudo apt-get install libfftw3-dev
        
    - name: Restore papreca executables
      uses: actions/download-artifact@v4
      with:
        name: papreca-artifacts_${{ needs.setCloneName.outputs.clone_name }} #use commit hash (enviromental variable captured in the reusable workflow)
        path: papreca_artifacts_${{ needs.setCloneName.outputs.clone_name }}
        merge-multiple: false

    - name: Run source tests
      run: |
        chmod +rwx $GITHUB_WORKSPACE/papreca_artifacts_${{ needs.setCloneName.outputs.clone_name }}/source_tests
        cd $GITHUB_WORKSPACE/tests/source\ tests/
        bash run_tests.sh $GITHUB_WORKSPACE/papreca_artifacts_${{ needs.setCloneName.outputs.clone_name }}

  hybridTest:
  
    needs:
      - setCloneName #required to retrieve the clone name
      - build-reusable
    
    runs-on: ubuntu-latest

    steps:

    - name: Checkout #Checkout PAPRECA repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install mpich
        sudo apt-get install libfftw3-dev
        
    - name: Restore papreca executables
      uses: actions/download-artifact@v4
      with:
        name: papreca-artifacts_${{ needs.setCloneName.outputs.clone_name }}
        path: papreca_artifacts_${{ needs.setCloneName.outputs.clone_name }}
        merge-multiple: false
        

    - name: Run hybrid test
      run: |
        chmod +rwx $GITHUB_WORKSPACE/papreca_artifacts_${{ needs.setCloneName.outputs.clone_name }}/papreca
        cd $GITHUB_WORKSPACE/tests/hybrid\ kMC\ MD/
        bash ./test_hybrid.sh $GITHUB_WORKSPACE/papreca_artifacts_${{ needs.setCloneName.outputs.clone_name }}


  eventTests:
  
    needs:
      - setCloneName #required to retrieve the clone name
      - build-reusable
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        seed: [52748145,27149655,45334679,217676174,161081677]

    steps:

    - name: Checkout #Checkout PAPRECA repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
          python-version: '3.x'
          architecture: 'x64'
           
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip numpy
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install mpich
        sudo apt-get install libfftw3-dev
        
    - name: Restore papreca executables
      uses: actions/download-artifact@v4
      with:
        name: papreca-artifacts_${{ needs.setCloneName.outputs.clone_name }}
        path: papreca_artifacts_${{ needs.setCloneName.outputs.clone_name }}
        merge-multiple: false
        

    - name: Run event test
      run: |
        chmod +rwx $GITHUB_WORKSPACE/papreca_artifacts_${{ needs.setCloneName.outputs.clone_name }}/papreca
        echo -e "Starting all event tests with seed: ${{ matrix.seed }}"
        cd $GITHUB_WORKSPACE/tests/event\ tests/
        bash test_all_events.sh ${{ matrix.seed }} $GITHUB_WORKSPACE/papreca_artifacts_${{ needs.setCloneName.outputs.clone_name }} python3
