name: Run tests

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
 push:
   branches:
     -main

jobs:
  installation:
    runs-on: ubuntu-latest
    steps:

     - name: Checkout
       uses: actions/checkout@v4 #Checkout repository
      
     - name: Install dependencies
       run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install mpich
        
     - name: Clone LAMMPS repository
       run: git clone -b release https://github.com/lammps/lammps.git mylammps
      
     - name: Build LAMMPS with required packages
       run: |
          cd mylammps
          git checkout release
          git pull
          mkdir build
          cd build
          cmake -DPKG_MOLECULE=on -DPKG_RIGID=on -D PKG_QEQ=on -DBUILD_LIB=on -DBUILD_SHARED_LIBS=off -DBUILD_STATIC_LIBS=on ../cmake #Configure LAMMPS, build with some optional package, and enable static library building 
          cmake --build .
     - name: Build PAPRECA
       run: |
          cd $HOME
          mkdir mypapreca
          cd ./mypapreca
          build mkdir
          cd build
          cmake $GITHUB_WORKSPACE/Installation/CMake -DLAMMPS_SRC_DIR=$HOME/mylammps/src/ -DLAMMPS_LIB_DIR=$HOME/mylammps/build/
          cmake --build .
          
          
