name: Run ALL tests

# Controls when the action will run.

on:
  workflow_dispatch: #Only trigger manually

jobs:
  runAllTests:
    runs-on: ubuntu-latest
    steps:

     - name: Checkout
       uses: actions/checkout@v4 #Checkout repository
      
     - name: Install dependencies
       run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install mpich
        
     - name: Clone LAMMPS repository
       run: |
        cd $HOME
        git clone -b release https://github.com/lammps/lammps.git mylammps
      
     - name: Build LAMMPS with required packages
       run: |
          cd $HOME/mylammps
          git checkout release
          git pull
          mkdir build; cd build
          cmake -DPKG_MOLECULE=on -DPKG_RIGID=on -D PKG_QEQ=on -DBUILD_LIB=on -DBUILD_SHARED_LIBS=off -DBUILD_STATIC_LIBS=on ../cmake #Configure LAMMPS, build all required packages to run tests and enable static library building 
          cmake --build .

     - name: Build PAPRECA
       run: |
          cd $HOME
          mkdir mypapreca; cd ./mypapreca
          mkdir build; cd build
          cmake $GITHUB_WORKSPACE/Installation/CMake -DLAMMPS_SRC_DIR=$HOME/mylammps/src/ -DLAMMPS_LIB_DIR=$HOME/mylammps/build/
          cmake --build .
          
     - name: Build TESTS executable for PAPRECA
       run: |
          cd $HOME
          cp -r $GITHUB_WORKSPACE/tests/ ./
          cd ./tests/source\ tests/
          mkdir build; cd build
          cmake .. -DLAMMPS_SRC_DIR=$HOME/mylammps/src/ -DLAMMPS_LIB_DIR=$HOME/mylammps/build/ -DPAPRECA_SRC_DIR=$GITHUB_WORKSPACE/source
          cmake --build .

     - name: Run source tests
       run: |
        cd $HOME/tests/source\ tests/
        bash ./run_tests.sh

     - name: Run all event tests for 5 different random seeds
       run: |
        cd $HOME/tests/event\ tests/
        echo -e "Starting test number 1"
        bash test_all_events.sh 52748145 $HOME/mypapreca/build python3
        echo -e "Starting test number 2"
        bash test_all_events.sh 27149655 $HOME/mypapreca/build python3
        echo -e "Starting test number 3"
        bash test_all_events.sh 45334679 $HOME/mypapreca/build python3
        echo -e "Starting test number 4"
        bash test_all_events.sh 217676174 $HOME/mypapreca/build python3
        echo -e "Starting test number 5"
        bash test_all_events.sh 161081677 $HOME/mypapreca/build python3
        
        

        
       
